"""
Markdown Mind Map Generator
Generates hierarchical markdown outline compatible with EdrawMind import
Also works with Markmap, Obsidian, and other markdown-based tools
"""
from io import BytesIO

from app.core.logging import get_logger
from app.utils.date_utils import get_vietnam_time
from app.services.mindmap.models import MindMapNode, MindMapTheme

logger = get_logger(__name__)


class MarkdownGenerator:
    """
    Generate mind map in Markdown format

    Benefits for EdrawMind:
    - Clean import with proper hierarchy
    - Human-readable format
    - Version control friendly
    - Can be edited in any text editor

    Output format:
    # Root Topic
    ## Branch 1
    - Detail 1.1
    - Detail 1.2
    ## Branch 2
    ### Sub-branch 2.1
    - Detail 2.1.1
    """

    async def generate(
        self,
        root: MindMapNode,
        title: str,
        theme: MindMapTheme
    ) -> BytesIO:
        """
        Generate Markdown mind map

        Args:
            root: Root node of the mind map
            title: Mind map title
            theme: Color theme (not used in Markdown but kept for interface consistency)

        Returns:
            BytesIO buffer with Markdown content
        """
        lines = []

        # Add metadata header as comment
        lines.append(f"<!-- Mind Map: {title} -->")
        lines.append(f"<!-- Generated by Mindmap Bot - {get_vietnam_time().strftime('%Y-%m-%d %H:%M')} -->")
        lines.append("")

        # Build markdown structure
        self._build_markdown(lines, root, depth=0)

        # Join lines
        markdown_str = '\n'.join(lines)

        # Create BytesIO buffer
        buffer = BytesIO(markdown_str.encode('utf-8'))
        buffer.seek(0)

        logger.info(f"Markdown generated: {title} ({len(markdown_str)} bytes)")
        return buffer

    def _build_markdown(self, lines: list, node: MindMapNode, depth: int):
        """
        Recursively build Markdown structure

        Depth mapping:
        - 0: # (H1) - Root
        - 1: ## (H2) - Main branches
        - 2: ### (H3) - Sub-branches
        - 3: #### (H4) - Sub-sub-branches
        - 4+: - (bullet points) - Details

        Args:
            lines: List to append lines to
            node: Current MindMapNode
            depth: Current depth level
        """
        if depth == 0:
            # Root node as H1
            lines.append(f"# {node.name}")
            if node.note:
                lines.append("")
                lines.append(f"> {node.note}")
            lines.append("")

        elif depth <= 4:
            # Use headings for first 4 levels
            heading = "#" * (depth + 1)
            lines.append(f"{heading} {node.name}")
            if node.note:
                lines.append("")
                lines.append(f"> {node.note}")
            lines.append("")

        else:
            # Use bullet points for deeper levels
            indent = "  " * (depth - 5)
            lines.append(f"{indent}- **{node.name}**")
            if node.note:
                lines.append(f"{indent}  - _{node.note}_")

        # Recursively add children
        for child in node.children:
            self._build_markdown(lines, child, depth + 1)

    async def generate_mermaid(
        self,
        root: MindMapNode,
        title: str,
        theme: MindMapTheme
    ) -> BytesIO:
        """
        Generate Mermaid mindmap syntax

        Useful for:
        - Web-based visualization
        - GitHub/GitLab markdown
        - Documentation

        Args:
            root: Root node of the mind map
            title: Mind map title
            theme: Color theme (not used)

        Returns:
            BytesIO buffer with Mermaid syntax
        """
        lines = []
        lines.append("```mermaid")
        lines.append("mindmap")

        # Build mermaid structure
        self._build_mermaid(lines, root, depth=1)

        lines.append("```")

        mermaid_str = '\n'.join(lines)

        buffer = BytesIO(mermaid_str.encode('utf-8'))
        buffer.seek(0)

        logger.info(f"Mermaid generated: {title} ({len(mermaid_str)} bytes)")
        return buffer

    def _build_mermaid(self, lines: list, node: MindMapNode, depth: int):
        """
        Build Mermaid mindmap syntax

        Mermaid mindmap format:
        mindmap
          root((Central Topic))
            Branch 1
              Leaf 1.1
              Leaf 1.2
            Branch 2

        Args:
            lines: List to append lines to
            node: Current MindMapNode
            depth: Current depth level (for indentation)
        """
        indent = "  " * depth

        # Format node name based on depth
        name = node.name.replace('"', "'")  # Escape quotes

        if depth == 1:
            # Root node with special shape
            lines.append(f'{indent}root(("{name}"))')
        else:
            # Regular nodes
            lines.append(f'{indent}{name}')

        # Recursively add children
        for child in node.children:
            self._build_mermaid(lines, child, depth + 1)


# Global instance
markdown_generator = MarkdownGenerator()
